### ISSUE TITLE
Default fields in uniqueAggregateIndex

### ISSUE THREAD

**Issue by younessbout** [AxonFramework/extension-mongo#8]
Hi guys,

I think that the default fields in **uniqueAggregateIndex** unique index should include the AggregateType also.

The problem raised for us comes from legacy systems, which in general have row ids as numeric values, and the Ids should be kept as they are. 

And the three field (**type**, **aggregateIdentifier**, **sequenceNumber**) index is safe and general purposed 

Best Regards

**Comment by smcvb** [comment]
Thanks for sharing this with us @younessbout.

Axon 2.0 used to have this combination of three fields as the index, adding the aggregate type to the mix.
In the development of Axon 3.0, we however decided against this format in favor of performance.

I've providing the reasoning about this on an Axon Framework issue, which you can find [here](https://github.com/AxonFramework/AxonFramework/issues/890#issuecomment-468586157).

Due to this stance, I will be closing this issue. 
Feel free to keep commenting if you feel strongly this should be changed in future releases.
